### ISSUE TITLE
Use with an electron app

### ISSUE THREAD

**Issue by danydev** [bugfender/BugfenderSDK-React-Sample#3]
Is it possible to use bugfender js sdk within an electron app?
I'm having the error "ReferenceError: window is not defined" while using it. It looks like bugfender assumes there is a global `window` (while when the process is [main](https://www.electronjs.org/docs/glossary#main-process) there is no window)

**Comment by jgimenez** [comment]
Hi @danydev , this SDK is only for web browsers at the moment. It uses several browser APIs so it won't work in a node environment
